language: python
cache:
  pip: true
  directories:
    - node_modules
before_install:
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
script:
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile lawlmart
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile lawlmart
  - yarn run update && yarn run update-api
